name: brewhand
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  dialog_flowtter: ^0.3.3
  
  cupertino_icons: ^1.0.8

  #upload image
  image_picker: ^0.8.7+5
  path_provider: ^2.0.15
  cached_network_image: ^3.2.3

  # Supabase (Firebase alternative)
  supabase_flutter: ^2.3.4   # Core Supabase functionality
  postgrest: ^2.0.1         # Database client
  gotrue: ^2.4.1           # Authentication client
  storage_client: ^2.0.1    # Storage client
  realtime_client: ^2.0.0   # Realtime updates
  supabase_auth_ui: ^0.3.0  # UI components for auth
  
  # FontAwesome icons for additional icon support
  flutter_vector_icons: ^2.0.0
  
  # Added flutter_svg for SVG support
  flutter_svg: ^2.0.9

  # For sharing content
  share_plus: ^7.2.1

  intl: ^0.18.1 #(for date formatting in brew_history_page.dart)
  
  # For local storage
  shared_preferences: ^2.2.2
  
  # For generating unique IDs
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Asset declaration for SVG files
  assets:
    - assets/my_brews.svg
    - assets/brew_master.svg
    - assets/brew_bot.svg
    - assets/brew_social.svg
    - assets/coffee_cup.svg
    - assets/Star.svg
    - assets/camera_icon.svg
    - assets/pour_over_icon.svg
    - assets/espresso_icon.svg
    - assets/moka_pot_icon.svg
    - assets/cold_brew_icon.svg